apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend # связываем deployment and Pod
  template:
    metadata:
      labels:
        app: backend # устанавливаем label на pod
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: springboot
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: backend
          image: nobugsme/nbank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4111

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend # сервис будет направлять трафик на поду у которых app=backend
  ports:
    - name: http
      protocol: TCP
      port: 4111
      targetPort: 4111
  type: NodePort #clusterIP (только внутри кластре), NodePort открывает порт на всех нодах кластера