name: Build and Push Docker Image

on:
  push:
    paths:
      - 'src/**'   # запуск только при изменениях в папке src
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Get commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          docker build -t gckjwdz9/nbank_tests:$COMMIT_HASH .

      - name: Push Docker image to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: bash infra/docker_compose/push-to-docker.sh $COMMIT_HASH
