name: Run tests

on: [ push, workflow_dispatch ]

jobs:
  run-tests:
    name: Set up services (review apps) and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up services
        run: |
          cd infra/docker_compose
          bash restart-docker.sh
          cd ../..

      - name: Run tests
        run: mvn clean test -q